// This file is auto-generated by @hey-api/openapi-ts

/**
 * AdminDocsOut
 */
export type AdminDocsOut = {
    /**
     * Documents
     */
    documents: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Total
     */
    total: number;
};

/**
 * AnswerRow
 */
export type AnswerRow = {
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
};

/**
 * AssessmentIn
 * Both submission shapes the route handler accepted, plus the honeypot.
 */
export type AssessmentIn = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Industry
     */
    industry?: string | null;
    /**
     * Risklevel
     */
    riskLevel?: string | null;
    scores?: ScoresIn | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Business
     */
    business?: string | null;
    /**
     * Mobile
     */
    mobile?: string | null;
    /**
     * Report Type
     */
    report_type?: string | null;
    /**
     * Answers
     */
    answers?: {
        [key: string]: unknown;
    } | null;
    result?: ResultIn | null;
    /**
     * Consentreport
     */
    consentReport?: boolean | null;
    /**
     * Consentnewsletter
     */
    consentNewsletter?: boolean | null;
    /**
     * Consentfollowup
     */
    consentFollowup?: boolean | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Answersummary
     */
    answerSummary?: Array<AnswerRow>;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * AssessmentOut
 */
export type AssessmentOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Reporttoken
     */
    reportToken?: string | null;
};

/**
 * AssessmentReportOut
 * The stored document as the report page consumed it (Appwrite-era field names).
 */
export type AssessmentReportOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Industry
     */
    industry: string;
    /**
     * Risk Level
     */
    risk_level: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Report Type
     */
    report_type?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Business Name
     */
    business_name?: string | null;
    /**
     * Verdict Band
     */
    verdict_band?: string | null;
    /**
     * Final Score
     */
    final_score?: number | null;
    /**
     * Overall Score
     */
    overall_score?: number | null;
    /**
     * Raw Score
     */
    raw_score?: number | null;
    /**
     * Data Exposure
     */
    data_exposure?: number | null;
    /**
     * Control Maturity
     */
    control_maturity?: number | null;
    /**
     * Operational Readiness
     */
    operational_readiness?: number | null;
    /**
     * Red Flags Json
     */
    red_flags_json?: string | null;
    /**
     * Immediate Actions Json
     */
    immediate_actions_json?: string | null;
    /**
     * Thirty Day Actions Json
     */
    thirty_day_actions_json?: string | null;
    /**
     * Answers Json
     */
    answers_json?: string | null;
    /**
     * Category Scores Json
     */
    category_scores_json?: string | null;
    /**
     * Report Token
     */
    report_token?: string | null;
    /**
     * Report Token Expires At
     */
    report_token_expires_at?: string | null;
};

/**
 * BloggerIn
 */
export type BloggerIn = {
    /**
     * Email
     */
    email?: unknown;
    /**
     * Name
     */
    name?: unknown;
    /**
     * Bio
     */
    bio?: unknown;
};

/**
 * BloggerPatchIn
 */
export type BloggerPatchIn = {
    /**
     * Active
     */
    active?: unknown;
};

/**
 * Body_outreach-import_contacts
 */
export type BodyOutreachImportContacts = {
    /**
     * File
     */
    file?: string | null;
};

/**
 * ContactIn
 */
export type ContactIn = {
    /**
     * Fullname
     */
    fullName?: string | null;
    /**
     * Workemail
     */
    workEmail?: string | null;
    /**
     * Mobilenumber
     */
    mobileNumber?: string | null;
    /**
     * Companyname
     */
    companyName?: string | null;
    /**
     * Industry
     */
    industry?: string | null;
    /**
     * Companysize
     */
    companySize?: string | null;
    /**
     * Issuesummary
     */
    issueSummary?: string | null;
    /**
     * Preferredcontact
     */
    preferredContact?: string | null;
    /**
     * Preferredtime
     */
    preferredTime?: string | null;
    /**
     * Consentcontact
     */
    consentContact?: boolean | null;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * DocsOut
 */
export type DocsOut = {
    /**
     * Docs
     */
    docs: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Total
     */
    total: number;
};

/**
 * EnrollOut
 */
export type EnrollOut = {
    /**
     * Factorid
     */
    factorId: string;
    /**
     * Qr
     */
    qr: string;
    /**
     * Secret
     */
    secret: string;
    /**
     * Otpauth Uri
     */
    otpauth_uri: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportOut
 */
export type ImportOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Total
     */
    total: number;
    /**
     * Inserted
     */
    inserted: number;
    /**
     * Duplicates
     */
    duplicates: number;
    /**
     * Invalid
     */
    invalid: number;
};

/**
 * IndexRequestIn
 */
export type IndexRequestIn = {
    /**
     * Url
     */
    url?: unknown;
};

/**
 * InfographicIn
 */
export type InfographicIn = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Lane
     */
    lane?: string | null;
    /**
     * Excerpt
     */
    excerpt?: string | null;
    /**
     * Section What Changed
     */
    section_what_changed?: string | null;
    /**
     * Section Law Says
     */
    section_law_says?: string | null;
    /**
     * Section Do Now
     */
    section_do_now?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | undefined;
};

/**
 * InspectIn
 */
export type InspectIn = {
    /**
     * Scope
     */
    scope?: unknown;
    /**
     * Submitsitemap
     */
    submitSitemap?: unknown;
};

/**
 * InviteIn
 */
export type InviteIn = {
    /**
     * Email
     */
    email?: string;
    /**
     * Name
     */
    name?: string;
    /**
     * Role
     */
    role?: string;
};

/**
 * InviteOut
 */
export type InviteOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Invite Url
     */
    invite_url: string;
    /**
     * Email Sent
     */
    email_sent: boolean;
    /**
     * Email Error
     */
    email_error?: string | null;
};

/**
 * LoginIn
 * Defaults instead of required fields: the TypeScript answered a missing field with
 * 400 and its own message, not a 422 validation envelope.
 */
export type LoginIn = {
    /**
     * Email
     */
    email?: string;
    /**
     * Password
     */
    password?: string;
};

/**
 * LoginOut
 */
export type LoginOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Step
     */
    step: 'enroll' | 'verify';
    /**
     * Role
     */
    role: string;
    /**
     * Pending Token
     */
    pending_token: string;
};

/**
 * NoticeCaptureOut
 */
export type NoticeCaptureOut = {
    /**
     * Success
     */
    success: boolean;
};

/**
 * NoticeEventOut
 */
export type NoticeEventOut = {
    /**
     * Ok
     */
    ok: boolean;
};

/**
 * OkOut
 */
export type OkOut = {
    /**
     * Success
     */
    success?: boolean;
};

/**
 * RecoverIn
 */
export type RecoverIn = {
    /**
     * Email
     */
    email?: string;
};

/**
 * RecoverOut
 */
export type RecoverOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string;
};

/**
 * ResultIn
 */
export type ResultIn = {
    /**
     * Rawscore
     */
    rawScore?: number | null;
    /**
     * Finalscore
     */
    finalScore?: number | null;
    /**
     * Verdictband
     */
    verdictBand?: string | null;
    /**
     * Verdictdescription
     */
    verdictDescription?: string | null;
    /**
     * Dataexposure
     */
    dataExposure?: number | null;
    /**
     * Controlmaturity
     */
    controlMaturity?: number | null;
    /**
     * Operationalreadiness
     */
    operationalReadiness?: number | null;
    /**
     * Categoryscores
     */
    categoryScores?: {
        [key: string]: number;
    } | null;
    /**
     * Redflagstriggered
     */
    redFlagsTriggered?: Array<string>;
    /**
     * Immediateactions
     */
    immediateActions?: Array<string>;
    /**
     * Thirtydayactions
     */
    thirtyDayActions?: Array<string>;
};

/**
 * ReviseIn
 */
export type ReviseIn = {
    /**
     * Sectionkey
     */
    sectionKey?: string | null;
    /**
     * Currentcontent
     */
    currentContent?: string | null;
    /**
     * Feedbacknote
     */
    feedbackNote?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Section What Changed
     */
    section_what_changed?: string | null;
    /**
     * Section Law Says
     */
    section_law_says?: string | null;
    /**
     * Section Do Now
     */
    section_do_now?: string | null;
    /**
     * Section Uncertain
     */
    section_uncertain?: string | null;
    /**
     * Section Mistakes
     */
    section_mistakes?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | undefined;
};

/**
 * RevokeOut
 */
export type RevokeOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Revoked
     */
    revoked: number;
};

/**
 * SaveIn
 */
export type SaveIn = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Title
     */
    title?: string;
    /**
     * Slug
     */
    slug?: string;
    /**
     * Excerpt
     */
    excerpt?: string;
    /**
     * Lane
     */
    lane?: string;
    /**
     * Author
     */
    author?: string;
    /**
     * Tags
     */
    tags?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Status
     */
    status?: string;
    /**
     * Section What Changed
     */
    section_what_changed?: string | null;
    /**
     * Section Law Says
     */
    section_law_says?: string | null;
    /**
     * Section Do Now
     */
    section_do_now?: string | null;
    /**
     * Section Uncertain
     */
    section_uncertain?: string | null;
    /**
     * Section Mistakes
     */
    section_mistakes?: string | null;
    /**
     * Primary Sources
     */
    primary_sources?: Array<unknown>;
    /**
     * Validated At
     */
    validated_at?: string | null;
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Score Legal Accuracy
     */
    score_legal_accuracy?: number;
    /**
     * Score Primary Source
     */
    score_primary_source?: number;
    /**
     * Score Currency
     */
    score_currency?: number;
    /**
     * Score Scope
     */
    score_scope?: number;
    /**
     * Score Operational
     */
    score_operational?: number;
    [key: string]: unknown | (string | null) | string | (string | null) | boolean | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | Array<unknown> | (string | null) | (string | null) | number | undefined;
};

/**
 * ScoresIn
 * Legacy industry-assessment scores (pre-engine submissions).
 */
export type ScoresIn = {
    /**
     * Applicability
     */
    applicability?: number | null;
    /**
     * Maturity
     */
    maturity?: number | null;
    /**
     * Risk
     */
    risk?: number | null;
    /**
     * Urgency
     */
    urgency?: number | null;
    /**
     * Overall
     */
    overall?: number | null;
};

/**
 * SendIn
 */
export type SendIn = {
    /**
     * Briefingid
     */
    briefingId?: string | null;
};

/**
 * SendReportIn
 */
export type SendReportIn = {
    /**
     * Assessmentid
     */
    assessmentId?: unknown;
    /**
     * Answersummary
     */
    answerSummary?: Array<AnswerRow>;
};

/**
 * SetPasswordIn
 */
export type SetPasswordIn = {
    /**
     * Token
     */
    token?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Password
     */
    password?: string;
};

/**
 * StatsOut
 */
export type StatsOut = {
    /**
     * Total
     */
    total: number;
    /**
     * Pending
     */
    pending: number;
    /**
     * Sent
     */
    sent: number;
    /**
     * Subscribed
     */
    subscribed: number;
    /**
     * Bounced
     */
    bounced: number;
    /**
     * Unsubscribed
     */
    unsubscribed: number;
    /**
     * Complained
     */
    complained: number;
};

/**
 * SubscribeIn
 */
export type SubscribeIn = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Industry
     */
    industry?: string | null;
    /**
     * Frequency
     */
    frequency?: string | null;
    /**
     * Consentemail
     */
    consentEmail?: boolean | null;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * SubscribeOut
 */
export type SubscribeOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Already
     */
    already: boolean;
    /**
     * Name
     */
    name: string;
};

/**
 * SuccessOut
 */
export type SuccessOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * SurveySubmitIn
 */
export type SurveySubmitIn = {
    /**
     * Answers
     */
    answers?: {
        [key: string]: unknown;
    } | null;
    /**
     * Score
     */
    score?: {
        [key: string]: unknown;
    } | null;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * TaskOut
 */
export type TaskOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Status
     */
    status: string;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * TemplateDownloadIn
 */
export type TemplateDownloadIn = {
    /**
     * Businessname
     */
    businessName?: string | null;
    /**
     * Employees
     */
    employees?: string | null;
    /**
     * Contactname
     */
    contactName?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Consentcontact
     */
    consentContact?: boolean | null;
    /**
     * Consentbriefings
     */
    consentBriefings?: boolean | null;
    /**
     * Templatename
     */
    templateName?: string | null;
    /**
     * Reporttoken
     */
    reportToken?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Inventorycsv
     */
    inventoryCsv?: string | null;
    /**
     * Nichename
     */
    nicheName?: string | null;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * TemplatesDownloadIn
 */
export type TemplatesDownloadIn = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Contactpersonname
     */
    contactPersonName?: string | null;
    /**
     * Businessname
     */
    businessName?: string | null;
    /**
     * Templateselected
     */
    templateSelected?: string | null;
    /**
     * Phonenumber
     */
    phoneNumber?: string | null;
    /**
     * Consentcontact
     */
    consentContact?: boolean | null;
    /**
     * Consentbriefings
     */
    consentBriefings?: boolean | null;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * TemplatesDownloadOut
 */
export type TemplatesDownloadOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Downloadurl
     */
    downloadUrl?: string | null;
    /**
     * Email
     */
    email?: boolean | null;
    /**
     * Whatsapp
     */
    whatsapp?: boolean | null;
};

/**
 * TokenIn
 */
export type TokenIn = {
    /**
     * Token
     */
    token?: unknown;
};

/**
 * UnsubscribeIn
 */
export type UnsubscribeIn = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Sig
     */
    sig?: string | null;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Totp Confirmed
     */
    totp_confirmed: boolean;
};

/**
 * UserPatch
 */
export type UserPatch = {
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
};

/**
 * ValidateIn
 */
export type ValidateIn = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Lane
     */
    lane?: string | null;
    /**
     * Section What Changed
     */
    section_what_changed?: string | null;
    /**
     * Section Law Says
     */
    section_law_says?: string | null;
    /**
     * Section Do Now
     */
    section_do_now?: string | null;
    /**
     * Section Uncertain
     */
    section_uncertain?: string | null;
    /**
     * Section Mistakes
     */
    section_mistakes?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | (string | null) | undefined;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyIn
 */
export type VerifyIn = {
    /**
     * Code
     */
    code?: string;
    /**
     * Factorid
     */
    factorId?: string | null;
};

/**
 * VerifyOut
 */
export type VerifyOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Role
     */
    role: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * WhitePaperIn
 */
export type WhitePaperIn = {
    /**
     * Fullname
     */
    fullName?: string | null;
    /**
     * Workemail
     */
    workEmail?: string | null;
    /**
     * Companyname
     */
    companyName?: string | null;
    /**
     * Industry
     */
    industry?: string | null;
    /**
     * Companysize
     */
    companySize?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Consentemail
     */
    consentEmail?: boolean | null;
    /**
     * Consentphone
     */
    consentPhone?: boolean | null;
    /**
     * Consentwebinars
     */
    consentWebinars?: boolean | null;
    /**
     * Hp Url
     */
    hp_url?: string | null;
};

/**
 * WhitePaperOut
 */
export type WhitePaperOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Downloadurl
     */
    downloadUrl?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Partial
     */
    partial?: boolean | null;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * UnsubscribeOut
 */
export type AppApiRoutesFormsUnsubscribeOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Already Removed
     */
    already_removed?: boolean | null;
};

/**
 * UnsubscribeOut
 */
export type AppApiRoutesOutreachUnsubscribeOut = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Already
     */
    already: boolean;
};

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type UtilsHealthCheckDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/db';
};

export type UtilsHealthCheckDbResponses = {
    /**
     * Response Utils-Health Check Db
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type UtilsHealthCheckDbResponse = UtilsHealthCheckDbResponses[keyof UtilsHealthCheckDbResponses];

export type AssessmentsSubmitAssessmentData = {
    body: AssessmentIn;
    path?: never;
    query?: never;
    url: '/api/v1/assessments';
};

export type AssessmentsSubmitAssessmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssessmentsSubmitAssessmentError = AssessmentsSubmitAssessmentErrors[keyof AssessmentsSubmitAssessmentErrors];

export type AssessmentsSubmitAssessmentResponses = {
    /**
     * Successful Response
     */
    200: AssessmentOut;
};

export type AssessmentsSubmitAssessmentResponse = AssessmentsSubmitAssessmentResponses[keyof AssessmentsSubmitAssessmentResponses];

export type AssessmentsGetReportData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/v1/assessments/report/{token}';
};

export type AssessmentsGetReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssessmentsGetReportError = AssessmentsGetReportErrors[keyof AssessmentsGetReportErrors];

export type AssessmentsGetReportResponses = {
    /**
     * Successful Response
     */
    200: AssessmentReportOut;
};

export type AssessmentsGetReportResponse = AssessmentsGetReportResponses[keyof AssessmentsGetReportResponses];

export type NoticesCaptureNoticeLeadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notices/capture';
};

export type NoticesCaptureNoticeLeadResponses = {
    /**
     * Successful Response
     */
    200: NoticeCaptureOut;
};

export type NoticesCaptureNoticeLeadResponse = NoticesCaptureNoticeLeadResponses[keyof NoticesCaptureNoticeLeadResponses];

export type NoticesRecordNoticeEventData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notices/events';
};

export type NoticesRecordNoticeEventResponses = {
    /**
     * Successful Response
     */
    200: NoticeEventOut;
};

export type NoticesRecordNoticeEventResponse = NoticesRecordNoticeEventResponses[keyof NoticesRecordNoticeEventResponses];

export type NoticesNoticePdfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notices/pdf';
};

export type NoticesNoticePdfResponses = {
    /**
     * The notice as a PDF
     */
    200: Blob | File;
};

export type NoticesNoticePdfResponse = NoticesNoticePdfResponses[keyof NoticesNoticePdfResponses];

export type AuthLoginData = {
    body: LoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginOut;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    200: OkOut;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthReadMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthReadMeResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type AuthReadMeResponse = AuthReadMeResponses[keyof AuthReadMeResponses];

export type AuthInviteData = {
    body: InviteIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/invite';
};

export type AuthInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthInviteError = AuthInviteErrors[keyof AuthInviteErrors];

export type AuthInviteResponses = {
    /**
     * Successful Response
     */
    200: InviteOut;
};

export type AuthInviteResponse = AuthInviteResponses[keyof AuthInviteResponses];

export type AuthRecoverData = {
    body: RecoverIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/recover';
};

export type AuthRecoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRecoverError = AuthRecoverErrors[keyof AuthRecoverErrors];

export type AuthRecoverResponses = {
    /**
     * Successful Response
     */
    200: RecoverOut;
};

export type AuthRecoverResponse = AuthRecoverResponses[keyof AuthRecoverResponses];

export type AuthSetPasswordData = {
    body: SetPasswordIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/set-password';
};

export type AuthSetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthSetPasswordError = AuthSetPasswordErrors[keyof AuthSetPasswordErrors];

export type AuthSetPasswordResponses = {
    /**
     * Successful Response
     */
    200: OkOut;
};

export type AuthSetPasswordResponse = AuthSetPasswordResponses[keyof AuthSetPasswordResponses];

export type AuthEnrollData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/mfa/enroll';
};

export type AuthEnrollResponses = {
    /**
     * Successful Response
     */
    200: EnrollOut;
};

export type AuthEnrollResponse = AuthEnrollResponses[keyof AuthEnrollResponses];

export type AuthVerifyData = {
    body: VerifyIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/mfa/verify';
};

export type AuthVerifyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthVerifyError = AuthVerifyErrors[keyof AuthVerifyErrors];

export type AuthVerifyResponses = {
    /**
     * Successful Response
     */
    200: VerifyOut;
};

export type AuthVerifyResponse = AuthVerifyResponses[keyof AuthVerifyResponses];

export type UsersListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UsersListUsersResponses = {
    /**
     * Response Users-List Users
     * Successful Response
     */
    200: Array<UserOut>;
};

export type UsersListUsersResponse = UsersListUsersResponses[keyof UsersListUsersResponses];

export type UsersPatchUserData = {
    body: UserPatch;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersPatchUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserError = UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type UsersPatchUserResponse = UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type UsersRevokeSessionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/revoke-sessions';
};

export type UsersRevokeSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRevokeSessionsError = UsersRevokeSessionsErrors[keyof UsersRevokeSessionsErrors];

export type UsersRevokeSessionsResponses = {
    /**
     * Successful Response
     */
    200: RevokeOut;
};

export type UsersRevokeSessionsResponse = UsersRevokeSessionsResponses[keyof UsersRevokeSessionsResponses];

export type UsersResetTotpData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/reset-totp';
};

export type UsersResetTotpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersResetTotpError = UsersResetTotpErrors[keyof UsersResetTotpErrors];

export type UsersResetTotpResponses = {
    /**
     * Successful Response
     */
    200: OkOut;
};

export type UsersResetTotpResponse = UsersResetTotpResponses[keyof UsersResetTotpResponses];

export type FormsSubmitContactData = {
    body: ContactIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/contact';
};

export type FormsSubmitContactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsSubmitContactError = FormsSubmitContactErrors[keyof FormsSubmitContactErrors];

export type FormsSubmitContactResponses = {
    /**
     * Successful Response
     */
    200: SuccessOut;
};

export type FormsSubmitContactResponse = FormsSubmitContactResponses[keyof FormsSubmitContactResponses];

export type FormsSubscribeData = {
    body: SubscribeIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/subscribe';
};

export type FormsSubscribeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsSubscribeError = FormsSubscribeErrors[keyof FormsSubscribeErrors];

export type FormsSubscribeResponses = {
    /**
     * Successful Response
     */
    200: SuccessOut;
};

export type FormsSubscribeResponse = FormsSubscribeResponses[keyof FormsSubscribeResponses];

export type FormsUnsubscribeData = {
    body: UnsubscribeIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/subscribers/unsubscribe';
};

export type FormsUnsubscribeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsUnsubscribeError = FormsUnsubscribeErrors[keyof FormsUnsubscribeErrors];

export type FormsUnsubscribeResponses = {
    /**
     * Successful Response
     */
    200: AppApiRoutesFormsUnsubscribeOut;
};

export type FormsUnsubscribeResponse = FormsUnsubscribeResponses[keyof FormsUnsubscribeResponses];

export type FormsSubmitSurveyData = {
    body: SurveySubmitIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/survey/submit';
};

export type FormsSubmitSurveyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsSubmitSurveyError = FormsSubmitSurveyErrors[keyof FormsSubmitSurveyErrors];

export type FormsSubmitSurveyResponses = {
    /**
     * Successful Response
     */
    200: SuccessOut;
};

export type FormsSubmitSurveyResponse = FormsSubmitSurveyResponses[keyof FormsSubmitSurveyResponses];

export type FormsTemplateDownloadData = {
    body: TemplateDownloadIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/template-download';
};

export type FormsTemplateDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsTemplateDownloadError = FormsTemplateDownloadErrors[keyof FormsTemplateDownloadErrors];

export type FormsTemplateDownloadResponses = {
    /**
     * Successful Response
     */
    200: SuccessOut;
};

export type FormsTemplateDownloadResponse = FormsTemplateDownloadResponses[keyof FormsTemplateDownloadResponses];

export type FormsTemplatesDownloadData = {
    body: TemplatesDownloadIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/templates/download';
};

export type FormsTemplatesDownloadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsTemplatesDownloadError = FormsTemplatesDownloadErrors[keyof FormsTemplatesDownloadErrors];

export type FormsTemplatesDownloadResponses = {
    /**
     * Successful Response
     */
    200: TemplatesDownloadOut;
};

export type FormsTemplatesDownloadResponse = FormsTemplatesDownloadResponses[keyof FormsTemplatesDownloadResponses];

export type FormsWhitePaperData = {
    body: WhitePaperIn;
    path?: never;
    query?: never;
    url: '/api/v1/forms/white-paper';
};

export type FormsWhitePaperErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FormsWhitePaperError = FormsWhitePaperErrors[keyof FormsWhitePaperErrors];

export type FormsWhitePaperResponses = {
    /**
     * Successful Response
     */
    200: WhitePaperOut;
};

export type FormsWhitePaperResponse = FormsWhitePaperResponses[keyof FormsWhitePaperResponses];

export type ChatChatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat';
};

export type ChatChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatFeedbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/feedback';
};

export type ChatFeedbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatHandoffData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/handoff';
};

export type ChatHandoffResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/health';
};

export type ChatHealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OutreachImportContactsData = {
    body?: BodyOutreachImportContacts;
    path?: never;
    query?: never;
    url: '/api/v1/outreach/import';
};

export type OutreachImportContactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachImportContactsError = OutreachImportContactsErrors[keyof OutreachImportContactsErrors];

export type OutreachImportContactsResponses = {
    /**
     * Successful Response
     */
    200: ImportOut;
};

export type OutreachImportContactsResponse = OutreachImportContactsResponses[keyof OutreachImportContactsResponses];

export type OutreachStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/outreach/stats';
};

export type OutreachStatsResponses = {
    /**
     * Successful Response
     */
    200: StatsOut;
};

export type OutreachStatsResponse = OutreachStatsResponses[keyof OutreachStatsResponses];

export type OutreachListContactsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/outreach/contacts';
};

export type OutreachListContactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachListContactsError = OutreachListContactsErrors[keyof OutreachListContactsErrors];

export type OutreachListContactsResponses = {
    /**
     * Response Outreach-List Contacts
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OutreachListContactsResponse = OutreachListContactsResponses[keyof OutreachListContactsResponses];

export type OutreachSubscribeData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/api/v1/outreach/subscribe';
};

export type OutreachSubscribeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachSubscribeError = OutreachSubscribeErrors[keyof OutreachSubscribeErrors];

export type OutreachSubscribeResponses = {
    /**
     * Successful Response
     */
    200: SubscribeOut;
};

export type OutreachSubscribeResponse = OutreachSubscribeResponses[keyof OutreachSubscribeResponses];

export type OutreachUnsubscribeData = {
    body: TokenIn;
    path?: never;
    query?: never;
    url: '/api/v1/outreach/unsubscribe';
};

export type OutreachUnsubscribeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachUnsubscribeError = OutreachUnsubscribeErrors[keyof OutreachUnsubscribeErrors];

export type OutreachUnsubscribeResponses = {
    /**
     * Successful Response
     */
    200: AppApiRoutesOutreachUnsubscribeOut;
};

export type OutreachUnsubscribeResponse = OutreachUnsubscribeResponses[keyof OutreachUnsubscribeResponses];

export type OutreachCronOutreachSendData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cron/outreach-send';
};

export type OutreachCronOutreachSendResponses = {
    /**
     * Response Outreach-Cron Outreach Send
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OutreachCronOutreachSendResponse = OutreachCronOutreachSendResponses[keyof OutreachCronOutreachSendResponses];

export type OutreachCronBriefingSendData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cron/briefing-send';
};

export type OutreachCronBriefingSendResponses = {
    /**
     * Response Outreach-Cron Briefing Send
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OutreachCronBriefingSendResponse = OutreachCronBriefingSendResponses[keyof OutreachCronBriefingSendResponses];

export type WebhooksResendWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/resend';
};

export type WebhooksResendWebhookResponses = {
    /**
     * Response Webhooks-Resend Webhook
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type WebhooksResendWebhookResponse = WebhooksResendWebhookResponses[keyof WebhooksResendWebhookResponses];

export type AdminReadTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/admin/tasks/{task_id}';
};

export type AdminReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminReadTaskError = AdminReadTaskErrors[keyof AdminReadTaskErrors];

export type AdminReadTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskOut;
};

export type AdminReadTaskResponse = AdminReadTaskResponses[keyof AdminReadTaskResponses];

export type AdminReadDataData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Collection
         */
        collection?: string;
        /**
         * Limit
         */
        limit?: string | null;
        /**
         * Source
         */
        source?: string | null;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/v1/admin/data';
};

export type AdminReadDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminReadDataError = AdminReadDataErrors[keyof AdminReadDataErrors];

export type AdminReadDataResponses = {
    /**
     * Response Admin-Read Data
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminReadDataResponse = AdminReadDataResponses[keyof AdminReadDataResponses];

export type AdminReadDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/dashboard';
};

export type AdminReadDashboardResponses = {
    /**
     * Response Admin-Read Dashboard
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminReadDashboardResponse = AdminReadDashboardResponses[keyof AdminReadDashboardResponses];

export type AdminListBloggersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/bloggers';
};

export type AdminListBloggersResponses = {
    /**
     * Response Admin-List Bloggers
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminListBloggersResponse = AdminListBloggersResponses[keyof AdminListBloggersResponses];

export type AdminInviteBloggerData = {
    body: BloggerIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/bloggers';
};

export type AdminInviteBloggerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminInviteBloggerError = AdminInviteBloggerErrors[keyof AdminInviteBloggerErrors];

export type AdminInviteBloggerResponses = {
    /**
     * Response Admin-Invite Blogger
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminInviteBloggerResponse = AdminInviteBloggerResponses[keyof AdminInviteBloggerResponses];

export type AdminDeleteBloggerData = {
    body?: never;
    path: {
        /**
         * Blogger Id
         */
        blogger_id: string;
    };
    query?: never;
    url: '/api/v1/admin/bloggers/{blogger_id}';
};

export type AdminDeleteBloggerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminDeleteBloggerError = AdminDeleteBloggerErrors[keyof AdminDeleteBloggerErrors];

export type AdminDeleteBloggerResponses = {
    /**
     * Response Admin-Delete Blogger
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminDeleteBloggerResponse = AdminDeleteBloggerResponses[keyof AdminDeleteBloggerResponses];

export type AdminSetBloggerActiveData = {
    body: BloggerPatchIn;
    path: {
        /**
         * Blogger Id
         */
        blogger_id: string;
    };
    query?: never;
    url: '/api/v1/admin/bloggers/{blogger_id}';
};

export type AdminSetBloggerActiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminSetBloggerActiveError = AdminSetBloggerActiveErrors[keyof AdminSetBloggerActiveErrors];

export type AdminSetBloggerActiveResponses = {
    /**
     * Response Admin-Set Blogger Active
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminSetBloggerActiveResponse = AdminSetBloggerActiveResponses[keyof AdminSetBloggerActiveResponses];

export type AdminSendReportData = {
    body: SendReportIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/send-report';
};

export type AdminSendReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminSendReportError = AdminSendReportErrors[keyof AdminSendReportErrors];

export type AdminSendReportResponses = {
    /**
     * Response Admin-Send Report
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminSendReportResponse = AdminSendReportResponses[keyof AdminSendReportResponses];

export type AeoRunPanelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/aeo-panel-run';
};

export type AeoRunPanelResponses = {
    /**
     * Response Aeo-Run Panel
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type AeoRunPanelResponse = AeoRunPanelResponses[keyof AeoRunPanelResponses];

export type SeoStartInspectionData = {
    /**
     * Body
     */
    body?: InspectIn | null;
    path?: never;
    query?: never;
    url: '/api/v1/admin/seo-inspect';
};

export type SeoStartInspectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SeoStartInspectionError = SeoStartInspectionErrors[keyof SeoStartInspectionErrors];

export type SeoStartInspectionResponses = {
    /**
     * Response Seo-Start Inspection
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type SeoStartInspectionResponse = SeoStartInspectionResponses[keyof SeoStartInspectionResponses];

export type SeoReadSeoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/seo';
};

export type SeoReadSeoResponses = {
    /**
     * Response Seo-Read Seo
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeoReadSeoResponse = SeoReadSeoResponses[keyof SeoReadSeoResponses];

export type SeoMarkRequestedData = {
    body: IndexRequestIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/seo/index-requests';
};

export type SeoMarkRequestedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SeoMarkRequestedError = SeoMarkRequestedErrors[keyof SeoMarkRequestedErrors];

export type SeoMarkRequestedResponses = {
    /**
     * Response Seo-Mark Requested
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SeoMarkRequestedResponse = SeoMarkRequestedResponses[keyof SeoMarkRequestedResponses];

export type BriefingsListPublishedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/briefings';
};

export type BriefingsListPublishedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsListPublishedError = BriefingsListPublishedErrors[keyof BriefingsListPublishedErrors];

export type BriefingsListPublishedResponses = {
    /**
     * Successful Response
     */
    200: DocsOut;
};

export type BriefingsListPublishedResponse = BriefingsListPublishedResponses[keyof BriefingsListPublishedResponses];

export type BriefingsGetBySlugData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/briefings/by-slug/{slug}';
};

export type BriefingsGetBySlugErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsGetBySlugError = BriefingsGetBySlugErrors[keyof BriefingsGetBySlugErrors];

export type BriefingsGetBySlugResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BriefingsListForAdminData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/briefings/admin/all';
};

export type BriefingsListForAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsListForAdminError = BriefingsListForAdminErrors[keyof BriefingsListForAdminErrors];

export type BriefingsListForAdminResponses = {
    /**
     * Successful Response
     */
    200: AdminDocsOut;
};

export type BriefingsListForAdminResponse = BriefingsListForAdminResponses[keyof BriefingsListForAdminResponses];

export type BriefingsGenerateDisabledData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/briefings/generate';
};

export type BriefingsGenerateDisabledErrors = {
    /**
     * Successful Response
     */
    410: unknown;
};

export type BriefingsGenerateData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Fordate
         */
        forDate?: string | null;
    };
    url: '/api/v1/briefings/generate';
};

export type BriefingsGenerateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsGenerateError = BriefingsGenerateErrors[keyof BriefingsGenerateErrors];

export type BriefingsGenerateResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BriefingsApproveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Token
         */
        token?: string | null;
        /**
         * Briefingid
         */
        briefingId?: string | null;
    };
    url: '/api/v1/briefings/approve';
};

export type BriefingsApproveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsApproveError = BriefingsApproveErrors[keyof BriefingsApproveErrors];

export type BriefingsSendData = {
    body: SendIn;
    path?: never;
    query?: never;
    url: '/api/v1/briefings/send';
};

export type BriefingsSendErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsSendError = BriefingsSendErrors[keyof BriefingsSendErrors];

export type BriefingsSendResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BriefingsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Id
         */
        id?: string | null;
    };
    url: '/api/v1/briefings/delete';
};

export type BriefingsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BriefingsDeleteError = BriefingsDeleteErrors[keyof BriefingsDeleteErrors];

export type BriefingsDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BriefingsTodayData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/briefings/today';
};

export type BriefingsTodayResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogListPublishedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lane
         */
        lane?: string | null;
        /**
         * Exclude Slug
         */
        exclude_slug?: string | null;
        /**
         * Order
         */
        order?: 'created' | 'updated';
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/blog';
};

export type BlogListPublishedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogListPublishedError = BlogListPublishedErrors[keyof BlogListPublishedErrors];

export type BlogListPublishedResponses = {
    /**
     * Successful Response
     */
    200: DocsOut;
};

export type BlogListPublishedResponse = BlogListPublishedResponses[keyof BlogListPublishedResponses];

export type BlogGetPublishedBySlugData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/blog/by-slug/{slug}';
};

export type BlogGetPublishedBySlugErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogGetPublishedBySlugError = BlogGetPublishedBySlugErrors[keyof BlogGetPublishedBySlugErrors];

export type BlogGetPublishedBySlugResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogListForAdminData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/blog/admin/all';
};

export type BlogListForAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogListForAdminError = BlogListForAdminErrors[keyof BlogListForAdminErrors];

export type BlogListForAdminResponses = {
    /**
     * Successful Response
     */
    200: AdminDocsOut;
};

export type BlogListForAdminResponse = BlogListForAdminResponses[keyof BlogListForAdminResponses];

export type BlogUpdatePostData = {
    body: SaveIn;
    path?: never;
    query?: never;
    url: '/api/v1/blog/save';
};

export type BlogUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogUpdatePostError = BlogUpdatePostErrors[keyof BlogUpdatePostErrors];

export type BlogUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogCreatePostData = {
    body: SaveIn;
    path?: never;
    query?: never;
    url: '/api/v1/blog/save';
};

export type BlogCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogCreatePostError = BlogCreatePostErrors[keyof BlogCreatePostErrors];

export type BlogCreatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogValidateData = {
    body: ValidateIn;
    path?: never;
    query?: never;
    url: '/api/v1/blog/validate';
};

export type BlogValidateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogValidateError = BlogValidateErrors[keyof BlogValidateErrors];

export type BlogValidateResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogReviseData = {
    body: ReviseIn;
    path?: never;
    query?: never;
    url: '/api/v1/blog/revise';
};

export type BlogReviseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogReviseError = BlogReviseErrors[keyof BlogReviseErrors];

export type BlogReviseResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogGenerateInfographicData = {
    body: InfographicIn;
    path?: never;
    query?: never;
    url: '/api/v1/blog/infographic';
};

export type BlogGenerateInfographicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogGenerateInfographicError = BlogGenerateInfographicErrors[keyof BlogGenerateInfographicErrors];

export type BlogGenerateInfographicResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BlogGetPostData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/blog/{id}';
};

export type BlogGetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BlogGetPostError = BlogGetPostErrors[keyof BlogGetPostErrors];

export type BlogGetPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};