"""The standalone DPDPA privacy notice document.

Port of `frontend/lib/notice-pack/{render,engine}.ts` (the server half only). The client
still renders the same document for "Copy HTML" and the browser-print fallback, so the
two must not drift: every string, tag and space here is the TypeScript's, character for
character. DPDPA wording is never rewritten.

Public surface:
    notice_document_html(state, eff_iso=None) -> str   full <html> document
    PDF_HEADER / PDF_FOOTER                            running header/footer templates
    PDF_MARGINS                                        the page box the route prints with
    slug_for_file(org) -> str                          download filename stem
"""

import re
from datetime import UTC, datetime
from typing import Final

from app.notice_pack.data import (
    CONTEXT_LABELS,
    MONTHS_EN,
    MONTHS_HI,
    RETENTION_FALLBACK,
    RETENTION_TEXT,
    SECTOR_LABELS,
    SECTOR_VCLAUSE,
    VENDOR_CLAUSE,
    VENDOR_PURPOSE,
)
from app.notice_pack.state import Lang, NoticeState

# Print-optimised styling. Mirrors the live `.doc` preview (notice-pack.css) but scoped
# for a standalone A4 document — no `.npb` wrapper, brand tokens inlined, page-break
# rules so headings don't strand at the foot of a page.
DOC_CSS: Final[str] = """
  *{box-sizing:border-box}
  html,body{margin:0;padding:0}
  body{font-family:Inter,-apple-system,"Segoe UI",Arial,sans-serif;color:#334155;line-height:1.6;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .doc{max-width:760px;margin:0 auto;padding:8px 4px}
  .doc h1.dt{font-size:21px;color:#121A2E;font-weight:700;letter-spacing:-.02em;margin:0 0 4px}
  .doc .dmeta{font-size:11.5px;color:#94A3B8;margin-bottom:18px}
  .doc h2.dh{font-size:14.5px;color:#121A2E;font-weight:700;margin:18px 0 6px;padding-top:13px;border-top:1px solid #E4E9F1;break-after:avoid;page-break-after:avoid}
  .doc h2.dh:first-of-type{border-top:none;padding-top:0}
  .doc p,.doc li{font-size:13px;color:#334155;line-height:1.6;orphans:3;widows:3}
  .doc ul{margin:5px 0;padding-left:18px}
  .doc li{margin-bottom:2px}
  .doc .muted{color:#94A3B8;font-style:italic}
  .doc .disc{margin-top:20px;padding-top:13px;border-top:1px dashed #CBD5E1;font-size:11.5px;color:#94A3B8}
  @page{size:A4;margin:18mm 16mm 20mm}
"""

# Branded running header/footer (Chromium header_template / footer_template). Kept tiny —
# Chromium renders these in a separate context with its own default font-size:0, so every
# style must be inline and explicit.
PDF_HEADER: Final[str] = """
  <div style="width:100%;font-family:Inter,Arial,sans-serif;font-size:8px;color:#94A3B8;padding:0 16mm;display:flex;justify-content:space-between;align-items:center">
    <span style="font-weight:700;color:#121A2E;letter-spacing:.02em">Saral<span style="color:#07B981">Privacy</span></span>
    <span>DPDPA Privacy Notice</span>
  </div>"""

PDF_FOOTER: Final[str] = """
  <div style="width:100%;font-family:Inter,Arial,sans-serif;font-size:8px;color:#94A3B8;padding:0 16mm;display:flex;justify-content:space-between;align-items:center">
    <span>Generated by SaralPrivacy — a practical draft, not legal advice. Review before publishing.</span>
    <span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span>
  </div>"""

PDF_MARGINS: Final[dict[str, str]] = {
    "top": "18mm",
    "bottom": "20mm",
    "left": "16mm",
    "right": "16mm",
}

# ── Localised chrome (engine.ts `H`) ─────────────────────────────────────────
_HEADINGS_EN: Final[tuple[str, ...]] = (
    "1. Who we are",
    "2. Personal data we collect",
    "3. Why we collect it",
    "4. How we collect it",
    "5. Sharing with service providers",
    "6. Children’s data",
    "7. How long we keep your data",
    "8. Consent & withdrawal",
    "9. Your rights",
    "10. Grievance & Data Protection Board",
    "11. Contact us",
    "12. Updates to this notice",
)
_HEADINGS_HI: Final[tuple[str, ...]] = (
    "1. हम कौन हैं",
    "2. हम कौन-सा डेटा एकत्र करते हैं",
    "3. हम इसे क्यों एकत्र करते हैं",
    "4. हम इसे कैसे एकत्र करते हैं",
    "5. सेवा प्रदाताओं के साथ साझा करना",
    "6. बच्चों का डेटा",
    "7. हम डेटा कब तक रखते हैं",
    "8. सहमति और वापसी",
    "9. आपके अधिकार",
    "10. शिकायत और डेटा संरक्षण बोर्ड",
    "11. संपर्क करें",
    "12. इस सूचना में बदलाव",
)

_EN: Final[dict[str, str]] = {
    "fallback_org": "[Your business]",
    "eff": "Effective date",
    "rights": (
        "You have the right to access the data we hold about you, correct or complete it, "
        "erase it where the law allows, withdraw consent as easily as you gave it, nominate "
        "someone to exercise your rights, and raise a grievance with our Officer."
    ),
    "child": (
        "We process children’s data only with verifiable parental or guardian consent, and "
        "never for behavioural monitoring or targeted advertising directed at children."
    ),
    "board": (
        "If we do not resolve your grievance, you may complain to the Data Protection Board "
        "of India in the manner prescribed under the DPDP Act and Rules."
    ),
    "disc": "This notice is generated for guidance and is not legal advice. Review it before publishing.",
    "retention_lead": "We keep your data ",
    "consent_lead": (
        "We process data on the basis of your consent (DPDPA §6). You can withdraw consent at any time"
    ),
    "updates": "We may update this notice from time to time; the latest version is shown here.",
}

_HI: Final[dict[str, str]] = {
    "fallback_org": "[आपका व्यवसाय]",
    "eff": "प्रभावी तिथि",
    "rights": (
        "आपके पास अपने डेटा तक पहुँच, सुधार, कानून अनुमति देने पर मिटाने, सहमति वापस लेने, "
        "अधिकार हेतु किसी को नामित करने और शिकायत दर्ज करने का अधिकार है।"
    ),
    "child": (
        "हम बच्चों का डेटा केवल माता-पिता/अभिभावक की सत्यापित सहमति से संसाधित करते हैं और "
        "उसका उपयोग ट्रैकिंग या लक्षित विज्ञापन हेतु नहीं करते।"
    ),
    "board": "यदि शिकायत हल नहीं होती, तो आप भारत के डेटा संरक्षण बोर्ड को शिकायत कर सकते हैं।",
    "disc": "यह सूचना मार्गदर्शन हेतु है, कानूनी सलाह नहीं। प्रकाशित करने से पहले समीक्षा करें।",
    "retention_lead": "हम आपका डेटा रखते हैं ",
    "consent_lead": "सहमति आधार पर। आप किसी भी समय सहमति वापस ले सकते हैं",
    "updates": "हम इस सूचना को समय-समय पर अद्यतन कर सकते हैं।",
}

NO_SHARING_CLAUSE: Final[str] = (
    "We do not share your personal data with third parties, except where required by law."
)
_SHARING_LEAD: Final[str] = (
    "We share personal data only with the following categories of service providers, "
    "and only for the purposes described:"
)
_VENDOR_PURPOSE_FALLBACK: Final[str] = "to deliver the services described in this notice"

# The Vercel function ran with TZ=UTC, so `toLocaleDateString` stamped the UTC calendar
# day. Kept as-is so a regenerated notice carries the same effective date as one exported
# before the rebuild. (Flagged in docs/build/status/notices.md.)
_DATE_TZ: Final = UTC


# ── engine.ts helpers ────────────────────────────────────────────────────────
def esc_html(s: str | None) -> str:
    """engine.ts `escHtml`: escapes `&`, `"` and `<` — deliberately not `>`."""
    return (s or "").replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;")


def slugify(s: str | None) -> str:
    """engine.ts `slugify`."""
    out = re.sub(r"[^a-z0-9]+", "-", (s or "").lower().strip())
    return out.strip("-")


def slug_for_file(org: str | None) -> str:
    """`slugForFile` from the PDF route: slugify, cap at 60 chars, fall back."""
    return slugify(org or "your-business")[:60] or "your-business"


def _title(lang: Lang, org: str) -> str:
    name = org or (_HI if lang == "hi" else _EN)["fallback_org"]
    return f"गोपनीयता सूचना — {name}" if lang == "hi" else f"Privacy Notice — {name}"


def _intro(lang: Lang, org: str) -> str:
    if lang == "hi":
        name = org or _HI["fallback_org"]
        return (
            f"{name} आपकी निजता का सम्मान करता है। यह सूचना बताती है कि हम कौन-सा व्यक्तिगत डेटा "
            "एकत्र करते हैं, क्यों, कैसे, और DPDPA, 2023 के तहत आपके अधिकार क्या हैं।"
        )
    name = org or _EN["fallback_org"]
    return (
        f'{name} ("we", "us", "our") respects your privacy and is the Data Fiduciary '
        "responsible for the personal data described here. This notice explains what personal "
        "data we collect, why and how, and the rights you have under India's Digital Personal "
        "Data Protection Act, 2023 (DPDPA)."
    )


def _effective_date(lang: Lang, eff: datetime | None) -> str:
    """`toLocaleDateString("en-IN"|"hi-IN", {day:"numeric", month:"long", year:"numeric"})`."""
    d = eff or datetime.now(UTC)
    if d.tzinfo is None:  # a naive ISO string means UTC, as `new Date(...)` on Vercel did
        d = d.replace(tzinfo=UTC)
    d = d.astimezone(_DATE_TZ)
    months = MONTHS_HI if lang == "hi" else MONTHS_EN
    return f"{d.day} {months[d.month - 1]} {d.year}"


def vclause(state: NoticeState) -> str:
    """engine.ts `vclause`."""
    if state.noVendors:
        return NO_SHARING_CLAUSE
    key = SECTOR_VCLAUSE.get(state.sector, "generic")
    return VENDOR_CLAUSE.get(key) or VENDOR_CLAUSE["generic"]


def ret_text(state: NoticeState) -> str:
    """engine.ts `retText`."""
    return RETENTION_TEXT.get(state.retention, RETENTION_FALLBACK)


def _sharing_html(state: NoticeState) -> str:
    """engine.ts `sharingHtml`."""
    if state.noVendors:
        return f"<p>{NO_SHARING_CLAUSE}</p>"
    if not state.vendors:
        return f"<p>{vclause(state)}</p>"
    items = "".join(
        f"<li><b>{esc_html(v)}</b> — {VENDOR_PURPOSE.get(v, _VENDOR_PURPOSE_FALLBACK)}</li>"
        for v in state.vendors
    )
    return f"<p>{_SHARING_LEAD}</p><ul>{items}</ul>"


def _list_html(values: list[str]) -> str:
    """engine.ts `li`."""
    if not values:
        return '<p class="muted">— not specified yet —</p>'
    return "<ul>" + "".join(f"<li>{esc_html(v)}</li>" for v in values) + "</ul>"


def build_notice(state: NoticeState, lang: Lang, eff_iso: datetime | None = None) -> str:
    """engine.ts `buildNotice` — the document body, without the <html> shell."""
    t = _HI if lang == "hi" else _EN
    headings = _HEADINGS_HI if lang == "hi" else _HEADINGS_EN
    n = state.org
    today = _effective_date(lang, eff_iso)
    sector_label = SECTOR_LABELS.get(state.sector) if state.sector else None

    website_meta = " · " + esc_html(state.website) if state.website else ""
    h = (
        f'<h1 class="dt">{_title(lang, n)}</h1>'
        f'<div class="dmeta">SP-NOTICE-2026-(draft) · v1.0 · {t["eff"]}: {today}{website_meta}</div>'
        f"<p>{_intro(lang, n)}</p>"
    )

    # §1 Who we are — proper-cased sector + website + grievance contact + optional address.
    who_we_are = (
        (esc_html(n) or "[business]")
        + (" is a " + esc_html(sector_label) if sector_label else "")
        + "."
    )
    if state.website:
        who_we_are += f" Website: {esc_html(state.website)}."
    if state.regAddress:
        who_we_are += f" Registered address: {esc_html(state.regAddress)}."
    if state.cName or state.cEmail:
        officer = esc_html(state.cName) or "our Grievance Officer"
        at_email = " at " + esc_html(state.cEmail) if state.cEmail else ""
        who_we_are += f" For privacy matters, contact {officer}{at_email}."
    h += f'<h2 class="dh">{headings[0]}</h2><p>{who_we_are}</p>'

    h += f'<h2 class="dh">{headings[1]}</h2>{_list_html(state.data)}'

    if state.data:
        purposes = "".join(
            f"<li><b>{esc_html(d)}</b> — {esc_html(state.purpose.get(d) or '…')}</li>"
            for d in state.data
        )
        purpose_html = f"<ul>{purposes}</ul>"
    else:
        purpose_html = '<p class="muted">— add purposes —</p>'
    h += f'<h2 class="dh">{headings[2]}</h2>{purpose_html}'

    context_labels = [CONTEXT_LABELS.get(k, k) for k in state.contexts]
    h += f'<h2 class="dh">{headings[3]}</h2>{_list_html(context_labels)}'

    h += f'<h2 class="dh">{headings[4]}</h2>{_sharing_html(state)}'

    if state.children == "Yes":
        h += f'<h2 class="dh">{headings[5]}</h2><p>{t["child"]}</p>'

    h += f'<h2 class="dh">{headings[6]}</h2><p>{t["retention_lead"]}{ret_text(state)}.</p>'

    w_contact = state.withdrawContact or state.cEmail
    withdraw_tail = f" — {esc_html(w_contact)}" if w_contact else ""
    h += f'<h2 class="dh">{headings[7]}</h2><p>{t["consent_lead"]}{withdraw_tail}.</p>'

    h += f'<h2 class="dh">{headings[8]}</h2><p>{t["rights"]}</p>'

    email_suffix = " · " + esc_html(state.cEmail) if state.cEmail else ""
    h += (
        f'<h2 class="dh">{headings[9]}</h2>'
        f"<p>{esc_html(state.cName) or '[Officer]'}{email_suffix}. {t['board']}</p>"
    )

    phone_suffix = " · " + esc_html(state.cPhone) if state.cPhone else ""
    h += (
        f'<h2 class="dh">{headings[10]}</h2>'
        f"<p>{esc_html(state.cName) or '[name]'}{email_suffix}{phone_suffix}</p>"
    )

    h += f'<h2 class="dh">{headings[11]}</h2><p>{t["updates"]}</p>'
    h += f'<p class="disc">{t["disc"]}</p>'
    return h


def notice_document_html(state: NoticeState, eff_iso: datetime | None = None) -> str:
    """render.ts `noticeDocumentHtml` — the full standalone document."""
    body = build_notice(state, state.lang, eff_iso)
    title = f"Privacy Notice — {state.org or 'Your business'}"
    return (
        f'<!doctype html><html lang="{state.lang}"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        f"<title>{esc_html(title)}</title><style>{DOC_CSS}</style></head>"
        f'<body><div class="doc">{body}</div></body></html>'
    )
