"use client";
import { useEffect, useMemo, useState } from "react";
import Gauge from "./Gauge";
import DiscoveryPack from "./pack/DiscoveryPack";
import { bandColor, resolveGroups, TAG_GROUP } from "@/lib/discovery/engine";
import { getNiche, TAG_LIB } from "@/lib/discovery/data";
import { buildRegister, type DiscoveryRegister } from "@/lib/discovery/register";
import { checklistFor } from "@/lib/discovery/checklist-map";
import { trackEvent } from "@/lib/analytics";
import type { ItemGroup, ScoreResult } from "@/lib/discovery/types";

// Build the full Discovery Pack as a 3-section CSV — Master Register + Retention
// Matrix + Data Risk Register — so the download mirrors what's on screen.
function buildPackCsv(reg: DiscoveryRegister, nicheName: string): string {
  const esc = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const row = (cells: unknown[]) => cells.map(esc).join(",");
  const lines: string[] = [
    `# DPDPA Personal Data Discovery Pack — ${nicheName} — generated by SaralPrivacy`,
    `# ${reg.counts.items} items · ${reg.counts.categories} categories · ${reg.counts.highRisk} high-risk · Suggested — validate before adoption. Not legal advice.`,
    "",
    "# 1. Master Personal Data Register",
    row(["Data item", "Description", "Principal", "Category", "Purpose", "Collection source", "Stored at", "Risk", "Risk reason", "Recommended action", "External recipients", "Status"]),
  ];
  for (const r of reg.rows)
    lines.push(row([r.dataItem, r.description, r.dataPrincipal, r.dataCategory, r.purpose, r.collectionSource, r.storedAt, r.riskLevel, r.riskReason, r.recommendedAction, r.externalRecipients.join("; "), r.status]));
  lines.push("", "# 2. Retention Matrix (Suggested — validate before adoption)",
    row(["Category", "Trigger (clock starts)", "As per DPDPA", "As per other law", "Other-law citation", "Status", "Disposal", "Systems affected"]));
  for (const r of reg.retention)
    lines.push(row([r.dataItem, r.retentionTrigger, r.dpdpaBaseline, r.otherLaw?.period ?? "None identified — erase when purpose served", r.otherLaw?.citation ?? "", r.status === "statutory_floor" ? "Statutory floor" : "You determine", r.disposalMethod, r.systemsAffected.join("; ")]));
  lines.push("", "# 3. Data Risk Register",
    row(["Risk", "Severity", "Priority", "Category", "Affected data", "Location / flow", "Reason", "Recommended control", "Suggested mapping question", "Mapping priority"]));
  for (const r of reg.risks)
    lines.push(row([r.risk, r.severity, r.priority, r.category, r.affectedData.join("; "), r.locationOrFlow, r.reason, r.recommendedControl, r.suggestedMappingQuestion, r.mappingPriority]));
  return lines.join("\r\n");
}

const VERDICTS: Record<string, string> = {
  Low: "Your controls look proportionate to the data you hold. Keep them documented and current.",
  Moderate: "A few gaps are widening your exposure. Most are quick, practical fixes.",
  High: "Several high-value data areas are running without enough safeguards. Worth acting on soon.",
  Critical: "You hold sensitive, high-value data with weak safeguards. This is the priority to fix.",
};

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;

function narrative(nicheId: string, r: ScoreResult): string {
  const n = getNiche(nicheId);
  const cats = r.categories.slice(0, 6);
  const catText = cats.length
    ? cats.slice(0, -1).join(", ") + (cats.length > 1 ? " and " : "") + cats[cats.length - 1]
    : "personal data";
  const hid = r.hiddenSelected.map((h) => h.item.toLowerCase());
  let hidText = "";
  if (hid.length) {
    const top = hid.slice(0, 5);
    hidText =
      " Your biggest hidden risk areas sit in " +
      (top.length > 1 ? top.slice(0, -1).join(", ") + " and " + top[top.length - 1] : top[0]) +
      ".";
  }
  return `${n?.name ?? "Businesses like yours"} typically work with several categories of digital personal data — ${catText}.${hidText}`;
}

type Stage = "cta" | "form" | "sent";

export default function ResultPanel({
  nicheId,
  result,
  selected,
  onRestart,
}: {
  nicheId: string;
  result: ScoreResult;
  selected: Set<string>;
  onRestart: () => void;
}) {
  const r = result;
  const color = bandColor(r.riskBand);
  const n = getNiche(nicheId);
  const nicheName = n?.name ?? "your business";

  // The confirmed items, grouped — powers both the on-screen map and the CSV.
  const mapGroups = useMemo<ItemGroup[]>(
    () =>
      resolveGroups(nicheId)
        .map((g) => ({ ...g, items: g.items.filter((i) => selected.has(i.id)) }))
        .filter((g) => g.items.length > 0),
    [nicheId, selected],
  );
  const checklist = checklistFor(nicheId);

  // The three-report Discovery Pack — pure derivation of the confirmed items.
  // Engine helpers are injected so the pure builder never imports the engine.
  const register = useMemo(
    () =>
      buildRegister({
        nicheId,
        nicheName,
        groups: mapGroups,
        selectedIds: selected,
        result: r,
        deps: {
          tagWeight: (t) => TAG_LIB[t]?.weight ?? 1,
          categoryName: (k) => TAG_GROUP[k],
        },
      }),
    [nicheId, nicheName, mapGroups, selected, r],
  );

  const [stage, setStage] = useState<Stage>("cta");
  const [form, setForm] = useState({
    businessName: "",
    contactName: "",
    phone: "",
    employees: "",
    email: "",
    consentBriefings: false,
  });
  const [emailErr, setEmailErr] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [hp, setHp] = useState(""); // honeypot — empty for real users

  // Capture on-screen completions (not just CSV downloaders). Fires once per result.
  useEffect(() => {
    trackEvent.discoveryComplete({ niche: nicheId, band: r.riskBand, score: r.final, items: r.selectedCount });
  }, [nicheId, r.riskBand, r.final, r.selectedCount]);

  function set<K extends keyof typeof form>(k: K, v: (typeof form)[K]) {
    setForm((f) => ({ ...f, [k]: v }));
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setApiError(null);
    if (!EMAIL_RE.test(form.email)) {
      setEmailErr(true);
      return;
    }
    setEmailErr(false);
    setSubmitting(true);
    const csv = buildPackCsv(register, nicheName);
    try {
      const res = await fetch("/api/proxy/api/v1/forms/template-download", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          businessName: form.businessName,
          employees: form.employees,
          contactName: form.contactName,
          phone: form.phone,
          email: form.email,
          consentContact: true,
          consentBriefings: form.consentBriefings,
          templateName: checklist.templateName,
          source: "discovery",
          reportToken: nicheId, // stores the niche id on the lead
          nicheName,
          inventoryCsv: csv, // emailed back to the user as an attachment
          hp_url: hp,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok && data.success) {
        trackEvent.discoveryInventoryDownload({ niche: nicheId });
        // Primary deliverable: the personal-data inventory as a CSV (client-side).
        const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${nicheId}-dpdpa-discovery-pack.csv`;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
        // Bonus: dedicated-pack niches also get the industry starter checklist PDF.
        if (checklist.dedicated) {
          const p = document.createElement("a");
          p.href = checklist.pdfPath;
          p.download = `${checklist.templateName}.pdf`;
          document.body.appendChild(p);
          p.click();
          p.remove();
        }
        setStage("sent");
      } else {
        setApiError(data.detail || data.error || "Something went wrong. Please try again.");
      }
    } catch {
      setApiError("Network error. Please check your connection and try again.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="result">
      {/* Bold headline result band */}
      <div className="result-hero" style={{ ["--band" as string]: color }}>
        <div className="rh-left">
          <div className="rh-eyebrow">Your DPDP data-risk read</div>
          <div className="rh-headline">
            <span className="rh-band" style={{ color }}>{r.riskBand}</span>
            <span className="rh-risk"> risk</span>
          </div>
          <p className="rh-verdict">{VERDICTS[r.riskBand]}</p>
          <div className="rh-meta">
            <span className="rh-conf">Confidence: <strong>{r.confidence}</strong></span>
            <span className="rh-dot" aria-hidden="true">·</span>
            <span>{nicheName} · benchmarked across 276 business types</span>
          </div>
        </div>
        <div className="rh-right">
          <Gauge score={r.final} band={r.riskBand} />
          <div className="rh-fixes">
            <span className="rh-fixnum" style={{ color }}>{r.fixCount}</span>
            <span className="rh-fixlbl">prioritized fixes<br />to act on</span>
          </div>
        </div>
      </div>

      {/* Metric-delta grid */}
      <div className="metric-grid">
        <div className="metric">
          <div className="metric-top">
            <span className="metric-num">{r.selectedCount}</span>
            <span className="metric-of">of {r.totalCount}</span>
          </div>
          <div className="metric-lbl">personal-data items you confirmed</div>
          <div className="metric-bar">
            <span style={{ width: (r.totalCount ? (r.selectedCount / r.totalCount) * 100 : 0) + "%" }} />
          </div>
        </div>
        <div className="metric">
          <div className="metric-top">
            <span className="metric-num" style={{ color: r.hiddenSelected.length ? "#E8704A" : "#07B981" }}>
              {r.hiddenSelected.length}
            </span>
            <span className="metric-of">of {r.hiddenAvailable}</span>
          </div>
          <div className="metric-lbl">often-missed data points in play</div>
          <div className="metric-bar hid">
            <span style={{ width: (r.hiddenAvailable ? (r.hiddenSelected.length / r.hiddenAvailable) * 100 : 0) + "%" }} />
          </div>
        </div>
        <div className="metric">
          <div className="metric-top"><span className="metric-num">{r.categories.length}</span></div>
          <div className="metric-lbl">categories of personal data</div>
          <div className="metric-sub">across customer, staff &amp; premises records</div>
        </div>
        <div className="metric accent">
          <div className="metric-top"><span className="metric-num" style={{ color }}>{r.highValueCount}</span></div>
          <div className="metric-lbl">high-value items needing safeguards</div>
          <div className="metric-sub">financial, health, children’s or biometric data</div>
        </div>
      </div>

      <p className="result-narrative">{narrative(nicheId, r)}</p>

      <p className="result-narrative-sub">{r.categories.slice(0, 6).join(" · ")}</p>

      {/* The three-report Personal Data Discovery Pack (Register · Retention · Risk)
          + prioritised actions + the Data-Mapping handoff seam. */}
      <DiscoveryPack register={register} />

      <div className="result-exposure">
        <span className="exp-icon" aria-hidden="true">▣</span>
        <p>
          Potential regulatory exposure may arise where reasonable security safeguards, notice, consent, breach
          response, or children’s data obligations are weak. This snapshot is a practical starting point, not a legal
          opinion.
        </p>
      </div>

      {/* Lead-gated CSV data-inventory download → reuses /api/v1/forms/template-download.
          Universal (every niche has a map); dedicated packs also get the checklist PDF. */}
      <div className="result-cta">
        {stage === "cta" && (
          <div className="cta-split">
            <div>
              <h3>Take your data inventory with you</h3>
              <p>
                Download the map above as an editable CSV — a ready-to-use DPDPA data inventory you can keep working in
                {checklist.dedicated ? `, plus the ${nicheName.toLowerCase()} starter checklist.` : "."}
              </p>
            </div>
            <button type="button" className="btn-primary" onClick={() => setStage("form")}>
              Download data inventory (CSV)
            </button>
          </div>
        )}

        {stage === "form" && (
          <form className="cta-form" onSubmit={submit} noValidate>
            <div>
              <h3>A few details to unlock your inventory</h3>
              <p>
                Your snapshot stays on screen. The CSV data inventory
                {checklist.dedicated ? " and starter checklist download" : " downloads"} right after.
              </p>
            </div>
            <div className="cta-form-grid">
              <div className={"cta-field" + (emailErr ? " invalid" : "")}>
                <label htmlFor="d-email">Work email</label>
                <input
                  id="d-email"
                  type="email"
                  value={form.email}
                  onChange={(e) => {
                    set("email", e.target.value);
                    if (emailErr) setEmailErr(false);
                  }}
                  placeholder="you@company.com"
                  aria-invalid={emailErr}
                  aria-describedby={emailErr ? "d-email-err" : undefined}
                  required
                />
                {emailErr && (
                  <span className="field-err" id="d-email-err">
                    Please enter a valid email address.
                  </span>
                )}
              </div>
              <div className="cta-field">
                <label htmlFor="d-biz">Business name</label>
                <input id="d-biz" value={form.businessName} onChange={(e) => set("businessName", e.target.value)} required />
              </div>
              <div className="cta-field">
                <label htmlFor="d-name">Your name</label>
                <input id="d-name" value={form.contactName} onChange={(e) => set("contactName", e.target.value)} required />
              </div>
              <div className="cta-field">
                <label htmlFor="d-phone">Phone</label>
                <input id="d-phone" type="tel" value={form.phone} onChange={(e) => set("phone", e.target.value)} required />
              </div>
              <div className="cta-field">
                <label htmlFor="d-emp">Team size</label>
                <select id="d-emp" value={form.employees} onChange={(e) => set("employees", e.target.value)} required>
                  <option value="" disabled>Select…</option>
                  <option value="1-10">1–10</option>
                  <option value="11-50">11–50</option>
                  <option value="51-200">51–200</option>
                  <option value="200+">200+</option>
                </select>
              </div>
            </div>
            <label className="cta-consent">
              <input
                type="checkbox"
                checked={form.consentBriefings}
                onChange={(e) => set("consentBriefings", e.target.checked)}
              />
              <span>Also send me SaralPrivacy’s practical DPDPA briefings (optional, unsubscribe anytime).</span>
            </label>
            {/* honeypot — hidden from humans; bots fill it and get silently dropped */}
            <input
              type="text"
              name="hp_url"
              value={hp}
              onChange={(e) => setHp(e.target.value)}
              tabIndex={-1}
              autoComplete="off"
              aria-hidden="true"
              style={{ position: "absolute", left: "-9999px", width: 1, height: 1, opacity: 0 }}
            />
            {apiError && <div className="form-error" role="alert">{apiError}</div>}
            <div>
              <button type="submit" className="btn-primary" disabled={submitting}>
                {submitting ? "Preparing download…" : "Download my data inventory"}
              </button>
            </div>
          </form>
        )}

        {stage === "sent" && (
          <div className="cta-sent">
            <div className="sent-tick" aria-hidden="true">✓</div>
            <div>
              <h3>Your data inventory is downloading.</h3>
              <p>
                Check your downloads for the CSV inventory
                {checklist.dedicated ? ` and the ${nicheName.toLowerCase()} starter checklist` : ""}. Ready to close
                these gaps for good? Take the full SaralPrivacy readiness assessment and turn this snapshot into a
                tracked, evidence-backed plan.
              </p>
            </div>
            <a className="btn-primary" href="/assessment">
              Take the full assessment
            </a>
          </div>
        )}
      </div>

      <button type="button" className="result-restart" onClick={onRestart}>
        ↺ Start over with a different business type
      </button>
    </div>
  );
}
