// Notice Pack Builder — shared document shell.
// Single source of truth for the standalone notice HTML used by BOTH the client
// (Copy HTML / browser-print fallback) and the server-side PDF route. buildNotice()
// is deterministic and dependency-free, so this module is safe on server + client.
import { buildNotice, escHtml } from "./engine";
import type { NPState } from "./types";

// Print-optimised styling. Mirrors the live `.doc` preview (notice-pack.css) but
// scoped for a standalone A4 document — no `.npb` wrapper, brand tokens inlined,
// page-break rules so headings don't strand at the foot of a page.
const DOC_CSS = `
  *{box-sizing:border-box}
  html,body{margin:0;padding:0}
  body{font-family:Inter,-apple-system,"Segoe UI",Arial,sans-serif;color:#334155;line-height:1.6;-webkit-print-color-adjust:exact;print-color-adjust:exact}
  .doc{max-width:760px;margin:0 auto;padding:8px 4px}
  .doc h1.dt{font-size:21px;color:#121A2E;font-weight:700;letter-spacing:-.02em;margin:0 0 4px}
  .doc .dmeta{font-size:11.5px;color:#94A3B8;margin-bottom:18px}
  .doc h2.dh{font-size:14.5px;color:#121A2E;font-weight:700;margin:18px 0 6px;padding-top:13px;border-top:1px solid #E4E9F1;break-after:avoid;page-break-after:avoid}
  .doc h2.dh:first-of-type{border-top:none;padding-top:0}
  .doc p,.doc li{font-size:13px;color:#334155;line-height:1.6;orphans:3;widows:3}
  .doc ul{margin:5px 0;padding-left:18px}
  .doc li{margin-bottom:2px}
  .doc .muted{color:#94A3B8;font-style:italic}
  .doc .disc{margin-top:20px;padding-top:13px;border-top:1px dashed #CBD5E1;font-size:11.5px;color:#94A3B8}
  @page{size:A4;margin:18mm 16mm 20mm}
`;

/**
 * Standalone notice document (full <html>). Used server-side by Puppeteer and as
 * the client Copy-HTML / print-fallback payload, so the two never drift.
 */
export function noticeDocumentHtml(S: NPState, opts: { effIso?: string } = {}): string {
  const body = buildNotice(S, S.lang, opts.effIso);
  const title = `Privacy Notice — ${S.org || "Your business"}`;
  return `<!doctype html><html lang="${S.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escHtml(
    title
  )}</title><style>${DOC_CSS}</style></head><body><div class="doc">${body}</div></body></html>`;
}

// Branded running header/footer for the PDF (Puppeteer headerTemplate/footerTemplate).
// Kept tiny — Puppeteer renders these in a separate context with its own default
// font-size:0, so every style must be inline and explicit.
export const PDF_HEADER = `
  <div style="width:100%;font-family:Inter,Arial,sans-serif;font-size:8px;color:#94A3B8;padding:0 16mm;display:flex;justify-content:space-between;align-items:center">
    <span style="font-weight:700;color:#121A2E;letter-spacing:.02em">Saral<span style="color:#07B981">Privacy</span></span>
    <span>DPDPA Privacy Notice</span>
  </div>`;

export const PDF_FOOTER = `
  <div style="width:100%;font-family:Inter,Arial,sans-serif;font-size:8px;color:#94A3B8;padding:0 16mm;display:flex;justify-content:space-between;align-items:center">
    <span>Generated by SaralPrivacy — a practical draft, not legal advice. Review before publishing.</span>
    <span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span>
  </div>`;
