"""wave 1 modules: auth forms assessments notices chat

Revision ID: 019fd8cf33f7
Revises: 0001
Create Date: 2026-09-18 06:17:16.212775
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = '019fd8cf33f7'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicability_score', sa.Float(), nullable=True),
    sa.Column('maturity_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('data_exposure', sa.Integer(), nullable=True),
    sa.Column('control_maturity', sa.Integer(), nullable=True),
    sa.Column('operational_readiness', sa.Integer(), nullable=True),
    sa.Column('consent_report', sa.Boolean(), nullable=True),
    sa.Column('consent_newsletter', sa.Boolean(), nullable=True),
    sa.Column('consent_followup', sa.Boolean(), nullable=True),
    sa.Column('verdict_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('q11_blocker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('q12_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('red_flags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('immediate_actions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thirty_day_actions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_scores_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_token_expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_sent_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_sent_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at_attr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_assessments_report_token'), 'assessments', ['report_token'], unique=False, schema='app')
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False, schema='app')
    op.create_table('notice_captures',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('business_name', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.BigInteger(), nullable=True),
    sa.Column('export_type', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('created_at_attr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='app'
    )
    op.create_index('ix_notice_captures_idx_created', 'notice_captures', ['created_at'], unique=False, schema='app')
    op.create_index('ix_notice_captures_idx_sector', 'notice_captures', ['sector'], unique=False, schema='app')
    op.create_index('ix_notice_captures_idx_source', 'notice_captures', ['source'], unique=False, schema='app')
    op.create_table('notice_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at_attr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='app'
    )
    op.create_index('ix_notice_events_idx_created', 'notice_events', ['created_at'], unique=False, schema='app')
    op.create_index('ix_notice_events_idx_name', 'notice_events', ['name'], unique=False, schema='app')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('totp_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_totp_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_table('chat_feedback',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sessionId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turnId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pageUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failureKind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redactedQuestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('consent_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privacy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('withdrawn_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_value', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('downloads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_email', sa.Boolean(), nullable=True),
    sa.Column('consent_phone', sa.Boolean(), nullable=True),
    sa.Column('consent_webinars', sa.Boolean(), nullable=True),
    sa.Column('privacy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at_attr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at_attr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribe_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('unsubscribe_token'),
    schema='ops'
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operating_footprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state_ut', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digital_personal_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_types', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_storage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('controls_in_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('readiness_self_view', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('biggest_blocker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('most_helpful_resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('wants_report', sa.Boolean(), nullable=True),
    sa.Column('consent_followup', sa.Boolean(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('template_downloads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employees', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consent_contact', sa.Boolean(), nullable=True),
    sa.Column('report_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at_attr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('invite_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_invite_tokens_token_hash'), 'invite_tokens', ['token_hash'], unique=True, schema='app')
    op.create_index(op.f('ix_app_invite_tokens_user_id'), 'invite_tokens', ['user_id'], unique=False, schema='app')
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###

    # ── Manual additions (orchestrator) ─────────────────────────────────────
    # forms: CHECK constraints SQLModel cannot express, copied from the Supabase DDL.
    op.create_check_constraint(
        "subscribers_consent_source_check", "subscribers",
        "consent_source in ('manual','assessment_form','intro_email_one_click','report_email_cta','admin_added')",
        schema="ops",
    )
    op.create_check_constraint(
        "subscribers_status_check", "subscribers",
        "status in ('active','unsubscribed','bounced','complained')",
        schema="ops",
    )
    op.create_index("ix_subscribers_sub_status_idx", "subscribers", ["status"], schema="ops")
    # notices: tables owned by the module but not yet read/written by any route.
    for table in ("notice_runs", "business_profiles", "dsar_requests"):
        op.execute(
            f"""
            create table app.{table} (
              id uuid primary key default ops.uuid_generate_v7(),
              legacy_id text unique,
              created_at timestamptz not null default now(),
              updated_at timestamptz not null default now(),
              payload jsonb
            )
            """
        )


def downgrade() -> None:
    for table in ("notice_runs", "business_profiles", "dsar_requests"):
        op.execute(f"drop table if exists app.{table}")
    op.drop_index("ix_subscribers_sub_status_idx", table_name="subscribers", schema="ops")
    op.drop_constraint("subscribers_status_check", "subscribers", schema="ops", type_="check")
    op.drop_constraint("subscribers_consent_source_check", "subscribers", schema="ops", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_sessions_user_id'), table_name='sessions', schema='app')
    op.drop_table('sessions', schema='app')
    op.drop_index(op.f('ix_app_invite_tokens_user_id'), table_name='invite_tokens', schema='app')
    op.drop_index(op.f('ix_app_invite_tokens_token_hash'), table_name='invite_tokens', schema='app')
    op.drop_table('invite_tokens', schema='app')
    op.drop_table('template_downloads', schema='ops')
    op.drop_table('survey_responses', schema='ops')
    op.drop_table('subscribers', schema='ops')
    op.drop_table('leads', schema='ops')
    op.drop_table('downloads', schema='ops')
    op.drop_table('consent_log', schema='ops')
    op.drop_table('chat_feedback', schema='ops')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    op.drop_index('ix_notice_events_idx_name', table_name='notice_events', schema='app')
    op.drop_index('ix_notice_events_idx_created', table_name='notice_events', schema='app')
    op.drop_table('notice_events', schema='app')
    op.drop_index('ix_notice_captures_idx_source', table_name='notice_captures', schema='app')
    op.drop_index('ix_notice_captures_idx_sector', table_name='notice_captures', schema='app')
    op.drop_index('ix_notice_captures_idx_created', table_name='notice_captures', schema='app')
    op.drop_table('notice_captures', schema='app')
    op.drop_index(op.f('ix_app_audit_log_actor_user_id'), table_name='audit_log', schema='app')
    op.drop_table('audit_log', schema='app')
    op.drop_index(op.f('ix_app_assessments_report_token'), table_name='assessments', schema='app')
    op.drop_table('assessments', schema='app')
    # ### end Alembic commands ###
