"""wave 2 modules: editorial outreach admin

Revision ID: c6358c0b0979
Revises: 019fd8cf33f7
Create Date: 2026-09-18 17:14:22.819088
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = 'c6358c0b0979'
down_revision = '019fd8cf33f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings_meta',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('action_checklist', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('approval_token', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_attr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('industries', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('read_time', sa.BigInteger(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('infographic_base64', sa.Text(), nullable=True),
    sa.Column('outreach_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='app'
    )
    op.create_index('ix_briefings_meta_slug_idx', 'briefings_meta', ['slug'], unique=False, schema='app')
    op.create_table('admin_tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('running', 'done', 'failed')", name='admin_tasks_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_index('ix_admin_tasks_kind_created', 'admin_tasks', ['kind', 'created_at'], unique=False, schema='ops')
    op.create_table('ai_citations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('week_num', sa.BigInteger(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('engine_label', sa.Text(), nullable=False),
    sa.Column('query_id', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('cited', sa.Text(), nullable=False),
    sa.Column('position', sa.BigInteger(), nullable=True),
    sa.Column('cited_page', sa.Text(), nullable=True),
    sa.Column('quote_type', sa.Text(), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('raw_citations', sa.Text(), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_index('ix_ai_citations_idx_date', 'ai_citations', ['date'], unique=False, schema='ops')
    op.create_index('ix_ai_citations_idx_engine', 'ai_citations', ['engine'], unique=False, schema='ops')
    op.create_index('ix_ai_citations_idx_run_id', 'ai_citations', ['run_id'], unique=False, schema='ops')
    op.create_table('blog_posts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('lane', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('industries', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('section_what_changed', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('section_law_says', sa.Text(), nullable=True),
    sa.Column('read_time', sa.BigInteger(), nullable=True),
    sa.Column('score_legal_accuracy', sa.BigInteger(), nullable=True),
    sa.Column('score_primary_source', sa.BigInteger(), nullable=True),
    sa.Column('score_currency', sa.BigInteger(), nullable=True),
    sa.Column('score_scope', sa.BigInteger(), nullable=True),
    sa.Column('score_operational', sa.BigInteger(), nullable=True),
    sa.Column('validation_score', sa.BigInteger(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.Column('infographic_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('blogger_accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('invite_token', sa.Text(), nullable=True),
    sa.Column('token_expires', sa.Text(), nullable=True),
    sa.Column('created_at_attr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_table('email_send_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('briefing_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resend_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_attr', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    schema='ops'
    )
    op.create_index(op.f('ix_ops_email_send_log_email_type'), 'email_send_log', ['email_type'], unique=False, schema='ops')
    op.create_index(op.f('ix_ops_email_send_log_recipient_email'), 'email_send_log', ['recipient_email'], unique=False, schema='ops')
    op.create_index(op.f('ix_ops_email_send_log_resend_message_id'), 'email_send_log', ['resend_message_id'], unique=False, schema='ops')
    op.create_index(op.f('ix_ops_email_send_log_sent_at'), 'email_send_log', ['sent_at'], unique=False, schema='ops')
    op.create_table('outreach_contacts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intro_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('magic_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at_attr', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('magic_token'),
    schema='ops'
    )
    op.create_index(op.f('ix_ops_outreach_contacts_status'), 'outreach_contacts', ['status'], unique=False, schema='ops')
    op.create_table('seo_index_requests',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url'),
    schema='ops'
    )
    op.create_table('seo_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inspected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sitemap_url_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sitemap_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict_code', sa.Text(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope in ('watchlist', 'newcomers', 'full')", name='seo_runs_scope_check'),
    sa.CheckConstraint("verdict_code in ('QUEUE_MOVED', 'STARVED', 'TOO_EARLY', 'INSUFFICIENT_DATA')", name='seo_runs_verdict_code_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='ops'
    )
    op.create_index('seo_runs_run_at', 'seo_runs', [sa.literal_column('run_at desc')], unique=False, schema='ops')
    op.create_table('seo_inspections',
    sa.Column('id', sa.Uuid(), server_default=sa.text('ops.uuid_generate_v7()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('watchlist', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('in_sitemap', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('coverage_state', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('indexing_state', sa.Text(), nullable=True),
    sa.Column('last_crawl_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_canonical', sa.Text(), nullable=True),
    sa.Column('user_canonical', sa.Text(), nullable=True),
    sa.Column('robots_txt_state', sa.Text(), nullable=True),
    sa.Column('page_fetch_state', sa.Text(), nullable=True),
    sa.Column('referring_urls', sa.Integer(), nullable=True),
    sa.Column('requested_indexing_at', sa.Date(), nullable=True),
    sa.Column('clicks_28d', sa.Integer(), nullable=True),
    sa.Column('impressions_28d', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("bucket in ('indexed', 'discovered', 'crawled_not_indexed', 'unknown', 'excluded', 'other', 'error')", name='seo_inspections_bucket_check'),
    sa.ForeignKeyConstraint(['run_id'], ['ops.seo_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'url'),
    schema='ops'
    )
    op.create_index('seo_inspections_run_bucket', 'seo_inspections', ['run_id', 'bucket'], unique=False, schema='ops')
    op.create_index('seo_inspections_url_run_at', 'seo_inspections', ['url', sa.literal_column('run_at desc')], unique=False, schema='ops')
    # ### end Alembic commands ###

    # ── Manual additions (orchestrator): outreach CHECKs from the Supabase DDL ──
    op.create_check_constraint(
        "outreach_contacts_status_check", "outreach_contacts",
        "status in ('pending','sent','subscribed','bounced','unsubscribed','complained','failed')",
        schema="ops",
    )
    op.create_check_constraint(
        "email_send_log_email_type_check", "email_send_log",
        "email_type in ('intro','briefing_daily','briefing_weekly','report','subscribe_confirmation','unsubscribe_confirmation')",
        schema="ops",
    )
    op.create_check_constraint(
        "email_send_log_status_check", "email_send_log",
        "status in ('sent','delivered','opened','clicked','bounced','complained')",
        schema="ops",
    )
    op.create_index("ix_outreach_contacts_created_idx", "outreach_contacts", ["created_at_attr"], schema="ops")


def downgrade() -> None:
    op.drop_index("ix_outreach_contacts_created_idx", table_name="outreach_contacts", schema="ops")
    op.drop_constraint("email_send_log_status_check", "email_send_log", schema="ops", type_="check")
    op.drop_constraint("email_send_log_email_type_check", "email_send_log", schema="ops", type_="check")
    op.drop_constraint("outreach_contacts_status_check", "outreach_contacts", schema="ops", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('seo_inspections_url_run_at', table_name='seo_inspections', schema='ops')
    op.drop_index('seo_inspections_run_bucket', table_name='seo_inspections', schema='ops')
    op.drop_table('seo_inspections', schema='ops')
    op.drop_index('seo_runs_run_at', table_name='seo_runs', schema='ops')
    op.drop_table('seo_runs', schema='ops')
    op.drop_table('seo_index_requests', schema='ops')
    op.drop_index(op.f('ix_ops_outreach_contacts_status'), table_name='outreach_contacts', schema='ops')
    op.drop_table('outreach_contacts', schema='ops')
    op.drop_index(op.f('ix_ops_email_send_log_sent_at'), table_name='email_send_log', schema='ops')
    op.drop_index(op.f('ix_ops_email_send_log_resend_message_id'), table_name='email_send_log', schema='ops')
    op.drop_index(op.f('ix_ops_email_send_log_recipient_email'), table_name='email_send_log', schema='ops')
    op.drop_index(op.f('ix_ops_email_send_log_email_type'), table_name='email_send_log', schema='ops')
    op.drop_table('email_send_log', schema='ops')
    op.drop_table('blogger_accounts', schema='ops')
    op.drop_table('blog_posts', schema='ops')
    op.drop_index('ix_ai_citations_idx_run_id', table_name='ai_citations', schema='ops')
    op.drop_index('ix_ai_citations_idx_engine', table_name='ai_citations', schema='ops')
    op.drop_index('ix_ai_citations_idx_date', table_name='ai_citations', schema='ops')
    op.drop_table('ai_citations', schema='ops')
    op.drop_index('ix_admin_tasks_kind_created', table_name='admin_tasks', schema='ops')
    op.drop_table('admin_tasks', schema='ops')
    op.drop_index('ix_briefings_meta_slug_idx', table_name='briefings_meta', schema='app')
    op.drop_table('briefings_meta', schema='app')
    # ### end Alembic commands ###
